# Generated by Django 4.2.7 on 2023-11-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('delay', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
